port = 10080
#port = 10081
user_token = "ppaass-rust"
proxy_addresses = ["8.214.90.87:80", "8.214.90.87:80"]
#proxy_addresses = ["127.0.0.1:9999"]
buffer_size = 4194304
max_frame_size = 8388608
master_thread_number = 32
worker_thread_number = 128
max_blocking_threads = 32
thread_timeout = 5
proxy_connect_timeout = 20
client_connection_max_idle = 300
proxy_connection_max_idle = 300
log_config = "log-agent.yaml"
