port = 80
#port = 9999
buffer_size = 65536
max_frame_size = 131072
master_thread_number = 32
worker_thread_number = 128
max_blocking_threads = 32
thread_timeout = 5
target_connect_timeout = 20
agent_connection_max_idle = 300
target_connection_max_idle = 300
log_config = "log-proxy.yaml"
