port = 10080
#port = 10081
user_token = "ppaass-rust"
proxy_addresses = ["8.214.90.87:80", "43.153.16.81:80"]
#proxy_addresses = ["43.135.166.168:80"]
#proxy_addresses = ["104.238.144.228:80"]
#proxy_addresses = ["127.0.0.1:9999"]
buffer_size = 131072
max_frame_size = 262144
thread_number = 2048
monitor_thread_number=8
max_blocking_threads = 32
thread_timeout = 5
proxy_connect_timeout = 20
client_connection_max_idle = 300
proxy_connection_max_idle = 300
log_dir = "./log"
log_file = "ppaass-agent.log"
